### ISSUE TITLE
Blueprint Description Bug

### ISSUE THREAD

**Issue by tgrafk12** [KitchenMods/KitchenLib#110]
**Describe the bug**
Blueprints are Missing Descriptions (Not the silly blurbs, but the actual info on what it does)

**To Reproduce**
1. Install latest Game Update
2. Only use HarmonyX and K-Lib
3. Load into a save with any blueprints.

**Expected behavior**
There should be descriptions on Blueprints when you hover over them, no idea why its doing this, but I had tried teaching new people yesterday and it was a pain to remember what exactly some things did...

**Other Installed Mods**
None (except dependency HarmonyX)

**Screenshots**
![with-k-lib](https://github.com/user-attachments/assets/e63a5911-7bd9-441d-85f6-b6856c96f83f)
![without-k-lib](https://github.com/user-attachments/assets/fe157e92-a1df-416e-977b-b7328fd47bd0)

**Additional context**
Using KitchenLib removes the Description of the Blueprint. This also applies to any modded kitchen blueprint as well.

**Comment by StarFluxGames** [comment]
![image](https://github.com/user-attachments/assets/5f77faae-1ab6-4d3e-95cb-8b49c54b2027)

https://steamcommunity.com/sharedfiles/filedetails/?id=2932799348
