### ISSUE TITLE
CustomGardenProfile.cs contains a incorrect implicit cast

### ISSUE THREAD

**Issue by ItsSharples** [KitchenMods/KitchenLib#22]
CustomGardenProfile compares a List<Item> with List<GardenProfile.SpawnProbability>.

GardenProfile.SpawnProbability is a struct containing an `Item` and `float`, so the List<GardenProfile.SpawnProbability> could be reduced into a List<Item>.

**Comment by StarFluxGames** [comment]
Should be fixed in 0.3.2
