### ISSUE TITLE
Crash on entering main menu

### ISSUE THREAD

**Issue by TheInfamousAlk** [KitchenMods/KitchenLib#52]
**Describe the bug**
Game crashing upon pressing P to start. Log file below, mentions kitchenlib specifically at the end in the crash section. 

[Player.log](https://github.com/KitchenMods/KitchenLib/files/11299873/Player.log)

**Comment by kkstalls** [comment]
This is also happening with my game.

**Comment by StarFluxGames** [comment]
I am unable to replicate this problem, could you please provide some steps to reproduce this reliably so I am able to test further?
I've seen some of these errors typically related to Harmony not loading, so try verifying your game files through Steam.

**Comment by maartenverheul** [comment]
Also mentioned here: https://steamcommunity.com/app/1599600/discussions/0/3821909708341542990/.  For some people installing the preferencesystem mod fixes the problem, for me it doesn't fully fix it unfortunately.

**Comment by StarFluxGames** [comment]
Good to see this isn't a KL issue.
